# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-17 14:45
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField()),
                ('date', models.DateField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choose_frequency', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('job_time', models.PositiveSmallIntegerField()),
                ('experiment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bevim.Experiment')),
            ],
        ),
    ]
