# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-02 20:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bevim', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acceleration',
            name='timestamp',
            field=models.DecimalField(decimal_places=2, max_digits=17),
        ),
        migrations.AlterField(
            model_name='amplitude',
            name='timestamp',
            field=models.DecimalField(decimal_places=2, max_digits=17),
        ),
        migrations.AlterField(
            model_name='frequency',
            name='timestamp',
            field=models.DecimalField(decimal_places=2, max_digits=17),
        ),
        migrations.AlterField(
            model_name='speed',
            name='timestamp',
            field=models.DecimalField(decimal_places=2, max_digits=17),
        ),
    ]
