# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-18 20:21
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bevim', '0002_auto_20161102_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acceleration',
            name='x_value',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='acceleration',
            name='y_value',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='acceleration',
            name='z_value',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='amplitude',
            name='x_value',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='amplitude',
            name='y_value',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='amplitude',
            name='z_value',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='frequency',
            name='x_value',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='frequency',
            name='y_value',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='frequency',
            name='z_value',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='job',
            name='choose_frequency',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Frequency'),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_time',
            field=models.PositiveSmallIntegerField(verbose_name='Time in seconds'),
        ),
        migrations.AlterField(
            model_name='speed',
            name='x_value',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='speed',
            name='y_value',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='speed',
            name='z_value',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
