# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-20 00:04
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bevim', '0002_auto_20161102_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='choose_frequency',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Frequency'),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_time',
            field=models.PositiveSmallIntegerField(verbose_name='Time in seconds'),
        ),
    ]
