# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-25 17:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bevim', '0003_auto_20161119_2204'),
        ('bevim', '0004_auto_20161119_1903'),
    ]

    operations = [
    ]
