# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-26 19:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bevim', '0004_auto_20160925_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='job',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bevim.Job'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sensor',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
