# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-09 02:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bevim', '0005_merge'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperimentFrequency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.IntegerField()),
                ('timestamp', models.IntegerField()),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bevim.Experiment', verbose_name='Experiment')),
            ],
        ),
    ]
